---
# https://app.vagrantup.com/boxes/search
use: swarm

plugins:
  - vagrant-aws
  - vagrant-vbguest
  - vai

vb: &vb
    nodes: 1
    name_prefix: 'test'
    box: bento/ubuntu-21.04
    ram: 512
    vcpu: 1
    disk: 1
    disk_size: 10
    box_check_update: false
    check_guest_additions: false
    synced_folder_disabled: false
    ip_addr: 192.168.2.
    netmask: 255.255.255.0
  # provisioner:
  #   - type: ansible
  #     ask_become_pass: false
  #     playbook: ./ansible/playbook.yml
  #     config_file: ./ansible/ansible.cfg
  #     inventory_path = ./inventory/local
  #   - shell:
  #     script: |
  #       echo Installing Docker...
  #       curl -sSL https://get.docker.com/ | sh
  #       sudo usermod -aG docker vagrant
  #   - shell:
  #     script: |
  #       echo Swarm Init...
  #       sudo docker swarm init --listen-addr #{subnet}#{manager_ip}:2377 --advertise-addr #{subnet}#{manager_ip}:2377
  #       sudo docker swarm join-token --quiet worker > /vagrant/worker_token
  #   - shell:
  #     script: |
  #       echo Swarm Join...
  #       sudo docker swarm join --token $(cat /vagrant/worker_token) #{p['subnet']}#{manager_ip}:2377

aws: &aws
    nodes: 1
    sync_disabled: true
    # vagrant box add aws-dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
    box: aws-dummy
    name_prefix: aws
    ssh_username: ubuntu
    keypair_name: AWS_KEYPAIR_NAME
    private_key_path: ~/.ssh/PATH/TO/AWS_KEYPAIR_NAME.pem
    associate_public_ip: true
    ami: ami-xxxxxxxxxxxxxxx
    region: AWS_REGION
    instance_type: t2.micro
    subnet_id: subnet-xxxxxxxxxxxxxxx
    security_group: sg-xxxxxxxxxxxxxxx
    tags:
      team: DevOps

docker: &docker
  - type: docker
    nodes: 1
    name_prefix: docker
    image: nginx
    ports:
      host: 8080
      guest: 80

vbox:
  - type: vb
    <<: *vb
    name_prefix: manager
    usb:
      - name: SanDisk
        vendorid: 0x0781
        productid: 0x5583

swarm:
  - type: vb
    <<: *vb
    name_prefix: manager
    ip_addr: 192.168.5.
  - type: vb
    <<: *vb
    nodes: 2
    name_prefix: worker
    ip_addr: 192.168.5.2

multi:
  - type: docker
    <<: *docker
  - type: docker
    <<: *docker
    nodes: 2
    name_prefix: alpine
    image: nginx
    ports:
      host: 8085
  - type: vb
    <<: *vb
    name_prefix: rtls
    ip_addr: 192.168.2.7