portainer_admin_port: 9000
portainer_tunnel_port: 8000
portainer_gfs_subdir: portainer
portainer_network_name: portainer_agent_network
portainer_volume_name: portainer_data
portainer_app_name: portainer
portainer_admin_password: password1234
portainer_agent_secret: mysecrettoken
portainer_agent_version: 2.9.2
portainer_version: 2.9.2
gluster_mount_path: /mnt/gfs
traefik_network_name: web
app_domain_name: docker.local