---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Ensure openssh-server is installed.
      package:
        name:
          - openssh-server
        state: present

- import_playbook: ../../playbooks/vas.yml
