---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
     - vas_variable: vas playbook completed succesfully!
  tasks:
    - name: Playbook assertion
      assert:
        that: "vas_variable == 'vas playbook completed succesfully!'"
