---
# https://app.vagrantup.com/boxes/search

# configuration to run
use: vas

# Plugins
# installed if not found
# https://www.vagrantup.com/docs/plugins, https://vagrant-lists.github.io/plugins.html
plugins:
  - vai
  - vagrant-vbguest
  # - vagrant-aws # required for type aws

### config templates
vb: &vb
  type: vb
  # virtualbox name, appended with node count (0 based, vb01)
  name_prefix: vb
  nodes: 1
  box: bento/ubuntu-21.04 # *REQUIRED as no base box is configured.
  ram: 512
  vcpu: 1
  disks: 0  # additional disks to attach
  disk_size: '50 GB'
  disk_type: 'SATA Controller'  # disk controller type, 'SATA Controller' or 'SCSI'
  box_check_update: false
  check_guest_additions: false
  synced_folder_disabled: true
  ip_addr: 192.168.2. # ipadress prefix, ip will be string concated by count of nodes, starting at 1
  netmask: 255.255.255.0
  # list of provisioners, ansible is always the last provisioner to run
  provisioner:
    - type: ansible
      ask_become_pass: true
      playbook: ../ansible/playbooks/vas.yml
      config_file: ../ansible/ansible.cfg
      inventory_path: ../ansible/inventory
    - type: vai
      path: ../ansible/inventory
      filename: vagrant_ansible_inventory

aws: &aws
  nodes: 1
  sync_disabled: true
  # vagrant box add aws-dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
  box: aws-dummy
  name_prefix: aws
  ssh_username: ubuntu
  keypair_name: AWS_KEYPAIR_NAME
  private_key_path: ~/.ssh/PATH/TO/AWS_KEYPAIR_NAME.pem
  associate_public_ip: true
  ami: ami-xxxxxxxxxxxxxxx
  region: AWS_REGION
  instance_type: t2.micro
  subnet_id: subnet-xxxxxxxxxxxxxxx
  security_group: sg-xxxxxxxxxxxxxxx
  tags:
    team: DevOps

docker: &docker
  type: docker
  nodes: 1
  name_prefix: alpine
  image: alpine
###

vas:
  - description: test 2 node vms
    <<: *vb
    nodes: 2

# sample configurations
# vbox_usb:
#   - description: Machine with usb
#     <<: *vb
#     name_prefix: vusb
#     usb:
#       - name: SanDisk
#         vendorid: 0x0781
#         productid: 0x5583

# nginx:
#   - description: nginx container exposing port 8080
#     <<: *docker
#     name_prefix: nginx
#     image: nginx
#     ports:
#       host: 8080
#       guest: 80

# vbox_docker:
#   - description: Machine with docker installed
#     <<: *vb
#     name_prefix: vdocker
#   - shell:
#     script: |
#       echo Installing Docker...
#       curl -sSL https://get.docker.com/ | sh
#       sudo usermod -aG docker vagrant