---
- name: Install HAProxy
  ansible.builtin.apt:
    name:
      - haproxy
    state: latest
    update_cache: yes

- name: Copy cert generation script to host
  ansible.builtin.template:
    src: generate_certs.j2
    dest: /tmp/generate_certs.sh
    mode: 0755

- name: Run cert generation script
  shell: /tmp/generate_certs.sh

- name: Create HAProxy config file
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0775

- name: Restart HAProxy service
  ansible.builtin.systemd:
    name: haproxy
    enabled: yes
    state: restarted
