---
- name: Check if Swarm has already been initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true

- name: Add Docker node to existing Swarm as worker
  shell: >
    docker swarm join
    --token {{ join_token }} {{ join_address }}
  when: swarm_status.rc != 0
  ignore_errors: true
