---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    - vas_variable: vas role completed succesfully!
  tasks:
    - name: Role assertion
      assert:
        that: "vas_variable == 'vas role completed succesfully!'"