galaxy_info:
  author: Kevin Edwards
  description: A sample role for vas
  role_name: vas
  namespace: kevinedwards
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
      versions:
      - all
    - name: Debian
      versions:
    - all
  galaxy_tags:
    - vagrant
    - ansible
    - shell
dependencies: []
