---
- name: Create a temporary directory
  tempfile:
    state: directory
    suffix: tmp
  register: tmpdir

- name: Install Docker Python library
  ansible.builtin.pip:
    name: docker

- name: Install Docker Dependencies
  ansible.builtin.apt:
    name:
      # - ntp
      - apt-transport-https
      - gnupg-agent
      - apache2-utils
      - software-properties-common
      - python3-pip
    state: latest
    update_cache: yes

- name: Get Docker key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add Docker packages to Repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
  tags: docker

- name: Install Docker-CE
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
  tags: docker

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: yes


- name: Start docker service, if not started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  ignore_errors: true

- name: Waiting for Docker service to become available
  ansible.builtin.wait_for:
    path: /var/run/docker.sock
