---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Ensure openssh-server is installed.
      ansible.builtin.package:
        name:
          - openssh-server
        state: present

  tasks:
    - name: "Include vas"
      include_role:
        name: "vas"